export const portfolioCards = [
  {
    img_desc1x: './images/portfolio/img_desc1x.jpg',
    img_desc2x: './images/portfolio/img_desc@2x.jpg',
    img_desc3x: './images/portfolio/img_desc@3x.jpg',
    img_tab1x: './images/portfolio/img_tab1x.jpg',
    img_tab2x: './images/portfolio/img_tab@2x.jpg',
    img_tab3x: './images/portfolio/img_tab@3x.jpg',
    img_mob1x: './images/portfolio/img_mob1x.jpg',
    img_mob2x: './images/portfolio/img_mob@2x.jpg',
    img_mob3x: './images/portfolio/img_mob@3x.jpg',
    title: 'Banking App Interface Concept',
    text: 'App',
    alt: 'Online banking',
    category: 'app',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },

  {
    img_desc1x: './images/portfolio/img-1_desc1x.jpg',
    img_desc2x: './images/portfolio/img-1_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-1_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-1_tab1x.jpg',
    img_tab2x: './images/portfolio/img-1_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-1_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-1_mob1x.jpg',
    img_mob2x: './images/portfolio/img-1_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-1_mob@3x.jpg',
    title: 'Cashless Payment',
    text: 'Marketing',
    alt: 'QR payment',
    category: 'marketing',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-2_desc1x.jpg',
    img_desc2x: './images/portfolio/img-2_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-2_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-2_tab1x.jpg',
    img_tab2x: './images/portfolio/img-2_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-2_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-2_mob1x.jpg',
    img_mob2x: './images/portfolio/img-2_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-2_mob@3x.jpg',
    title: 'Meditation App',
    text: 'App',
    alt: 'Laptop and phone',
    category: 'app',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-3_desc1x.jpg',
    img_desc2x: './images/portfolio/img-3_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-3_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-3_tab1x.jpg',
    img_tab2x: './images/portfolio/img-3_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-3_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-3_mob1x.jpg',
    img_mob2x: './images/portfolio/img-3_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-3_mob@3x.jpg',
    title: 'Taxi Service',
    text: 'Marketing',
    alt: 'Car interior',
    category: 'marketing',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-4_desc1x.jpg',
    img_desc2x: './images/portfolio/img-4_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-4_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-4_tab1x.jpg',
    img_tab2x: './images/portfolio/img-4_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-4_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-4_mob1x.jpg',
    img_mob2x: './images/portfolio/img-4_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-4_mob@3x.jpg',
    title: 'Screen Illustrations',
    text: 'Design',
    alt: 'Phone with screensavers',
    category: 'design',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-5_desc1x.jpg',
    img_desc2x: './images/portfolio/img-5_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-5_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-5_tab1x.jpg',
    img_tab2x: './images/portfolio/img-5_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-5_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-5_mob1x.jpg',
    img_mob2x: './images/portfolio/img-5_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-5_mob@3x.jpg',
    title: 'Online Courses',
    text: 'Marketing',
    alt: 'Lucky girl with a phone',
    category: 'marketing',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-6_desc1x.jpg',
    img_desc2x: './images/portfolio/img-6_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-6_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-6_tab1x.jpg',
    img_tab2x: './images/portfolio/img-6_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-6_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-6_mob1x.jpg',
    img_mob2x: './images/portfolio/img-6_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-6_mob@3x.jpg',
    title: 'Instagram Stories Concept',
    text: 'Design',
    alt: 'Options for social media posts',
    category: 'design',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-7_desc1x.jpg',
    img_desc2x: './images/portfolio/img-7_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-7_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-7_tab1x.jpg',
    img_tab2x: './images/portfolio/img-7_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-7_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-7_mob1x.jpg',
    img_mob2x: './images/portfolio/img-7_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-7_mob@3x.jpg',
    title: 'Organic Food',
    text: 'Web Site',
    alt: 'Girl with a fruit basket',
    category: 'website',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
  {
    img_desc1x: './images/portfolio/img-8_desc1x.jpg',
    img_desc2x: './images/portfolio/img-8_desc@2x.jpg',
    img_desc3x: './images/portfolio/img-8_desc@3x.jpg',
    img_tab1x: './images/portfolio/img-8_tab1x.jpg',
    img_tab2x: './images/portfolio/img-8_tab@2x.jpg',
    img_tab3x: './images/portfolio/img-8_tab@3x.jpg',
    img_mob1x: './images/portfolio/img-8_mob1x.jpg',
    img_mob2x: './images/portfolio/img-8_mob@2x.jpg',
    img_mob3x: './images/portfolio/img-8_mob@3x.jpg',
    title: 'Fresh Coffee',
    text: 'Web Site',
    alt: 'Coffee cup',
    category: 'website',
    overlay:
      '14 Stylish and User-Friendly App Design Concepts · Task · Manager App · Calorie Tracker App · Exotic Fruit Ecommerce App · Cloud Storage App',
  },
];
